### ISSUE TITLE
casa-casacore has unmet dependencies

### ISSUE THREAD

**Issue by jfunction** [radio-astro-debian/casacore-debian#3]
Hi - not sure if I'm posting this in the right place. I am using Ubuntu 14.04 and recently (roughly the beginning of May) added the radio-astro ppa and installed meqtrees/pyxis/etc. I checked to see that things were working in iPython and indeed I can load and use measurement sets, it works great. 

I then tried to locate casacores .h files (which I need for development) but couldn't. Someone told me that I should try to install casacore, so I ran `sudo apt-get install casa-casacore` but I got a curious result:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 casa-casacore : Depends: libcasa-casacore1 (= 4.2.2-2trusty) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
By the way, I should also mention another thing I looked at:
```[bash]
{14:30}~ ➭ locate libcasa
/usr/lib/libcasa_casa.so.1
/usr/lib/libcasa_casa.so.1.7.0
/usr/lib/libcasa_components.so.1
/usr/lib/libcasa_components.so.1.7.0
/usr/lib/libcasa_coordinates.so.1
/usr/lib/libcasa_coordinates.so.1.7.0
/usr/lib/libcasa_derivedmscal.so.1
/usr/lib/libcasa_derivedmscal.so.1.7.0
/usr/lib/libcasa_fits.so.1
/usr/lib/libcasa_fits.so.1.7.0
/usr/lib/libcasa_images.so.1
/usr/lib/libcasa_images.so.1.7.0
/usr/lib/libcasa_lattices.so.1
/usr/lib/libcasa_lattices.so.1.7.0
/usr/lib/libcasa_meas.so.1
/usr/lib/libcasa_meas.so.1.7.0
/usr/lib/libcasa_measures.so.1
/usr/lib/libcasa_measures.so.1.7.0
/usr/lib/libcasa_mirlib.so.1
/usr/lib/libcasa_mirlib.so.1.7.0
/usr/lib/libcasa_ms.so.1
/usr/lib/libcasa_ms.so.1.7.0
/usr/lib/libcasa_msfits.so.1
/usr/lib/libcasa_msfits.so.1.7.0
/usr/lib/libcasa_scimath.so.1
/usr/lib/libcasa_scimath.so.1.7.0
/usr/lib/libcasa_scimath_f.so.1
/usr/lib/libcasa_scimath_f.so.1.7.0
/usr/lib/libcasa_tables.so.1
/usr/lib/libcasa_tables.so.1.7.0
/usr/share/doc/libcasacore1
/usr/share/doc/libcasacore1/changelog.Debian.gz
/usr/share/doc/libcasacore1/copyright
/var/lib/dpkg/info/libcasacore1.list
/var/lib/dpkg/info/libcasacore1.md5sums
/var/lib/dpkg/info/libcasacore1.postinst
/var/lib/dpkg/info/libcasacore1.postrm
/var/lib/dpkg/info/libcasacore1.shlibs
```

Any ideas?

**Comment by jfunction** [comment]
Digging through this repo it seems like `libcasacore-dev` was the thing I wanted to install... I did that and then installed `casacore` and now I can see some .h files under /usr/include/casacore... hooray :)

I'm still not sure what the error I was getting about unmet deps means or if that's going to be a problem for others, but I don't think I needed to install `casa-casacore` in the first place.

**Comment by gijzelaerr** [comment]
I don't think you want to install the casa-casacore packages. They are the casacore used by casa. It is a bit confusing :) most people just want to use the normale casacore packages.
