### ISSUE TITLE
libcasacore-dev clashes with casarest

### ISSUE THREAD

**Issue by o-smirnov** [radio-astro-debian/casacore-debian#6]
``Unpacking libcasacore-dev (1.7.0-2trusty) ...
dpkg: error processing archive /var/cache/apt/archives/libcasacore-dev_1.7.0-2trusty_amd64.deb (--unpack):
trying to overwrite '/usr/lib/libcasa_components.so', which is also in package casarest 1.3.1-2trusty
``

**Comment by gijzelaerr** [comment]
Yeah true. You can only install casacore2 and casarest at the same time.

Op zo 6 sep. 2015 19:43 schreef Oleg Smirnov <notifications@github.com>:

**Comment by o-smirnov** [comment]
So is there a way to mark this in the package metadata, so it doesn't
degenerate into puzzling dpkg errors?

**Comment by gijzelaerr** [comment]
Yep, will do.

Op zo 6 sep. 2015 19:47 schreef Oleg Smirnov <notifications@github.com>:

**Comment by gijzelaerr** [comment]
this has been resolved and casacore 1.7 packages will be removed from PPA
